version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reference-data-service
    image: node:16
    restart: always
    ports:
      - '3002:3002'
    networks:
      - spos-net
volumes:
  db:
    driver: local
networks:
  spos-net:
      name: spos-net